name: Four Season Agency
favicon: null
layout_spectrum: 0.5855209447909147
typography_spectrum: 0.05026602139696479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6090292045846581
  lightness: 0.710447188001126
  saturation: 0.9295515667181462
  rhythmicContrast: 0.8683514641597867
purpose: []
